In [1]:
import requests
import json
import random
import time
import pickle


model = "dRIT"

template = {
  "Answer": "",
  "Score Lexical Semantics": "",
  "Score Predicate-Argument Structure": "",
  "Score Logic": "",
  "Score Knowledge & Common Sense": ""
}

# TEST de SICK

In [2]:
import pandas as pd

In [3]:
df =pd.read_pickle("predictions/RL_SICK_TEST_with_prediction.pickle")
df

,relation,no_matcheadas,contradiction,jaccard,simBoW,sumas,mutinf_t,max_info_t,entail,list_comp,list_incomp,Jaro-Winkler_rit,negT,negH,overlap_ent,clases,predictions
0,-1,0.714286,0.142857,0.000000,0.316228,0.101323,4.041253,0.448079,0.500000,2,0,0.491667,0,0,0.142857,NEUTRAL,2
1,2,0.750000,0.000000,0.666667,0.428571,0.106182,4.217714,0.578176,0.714286,2,0,0.589286,0,0,0.250000,NEUTRAL,2
2,-1,0.750000,0.250000,0.333333,0.285714,0.083118,4.088408,0.490766,0.714286,3,0,0.507937,0,0,0.000000,NEUTRAL,2
3,1,0.000000,0.000000,1.000000,0.925820,0.184760,4.683008,1.000000,1.000000,0,0,0.952381,0,0,1.000000,ENTAILMENT,1
4,2,0.166667,0.000000,0.833333,0.833333,0.151210,4.574526,0.867853,0.857143,0,0,0.822222,0,0,0.833333,NEUTRAL,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4901,-1,0.666667,0.333333,0.250000,0.223607,0.043145,4.076415,0.335569,0.250000,0,0,0.483333,0,0,0.000000,NEUTRAL,2
4902,2,1.000000,0.000000,0.000000,0.000000,0.051206,3.770053,0.122140,0.500000,2,0,0.344444,0,0,0.000000,NEUTRAL,2
4903,2,1.000000,0.000000,0.000000,0.000000,-0.019122,3.697886,0.101417,0.400000,2,0,0.000000,0,0,0.000000,NEUTRAL,2
4904,2,1.000000,0.000000,0.000000,0.000000,-0.017080,3.848196,0.146788,0.250000,2,0,0.420635,0,0,0.000000,NEUTRAL,2
4905,2,1.000000,0.000000,0.000000,0.000000,0.010754,3.770119,0.156880,0.200000,1,0,0.280952,0,0,0.000000,NEUTRAL,2

In [ ]:
original =pd.read_csv("../RIT_ollama/SICK/SICK_TEST.csv")
original

,sentence_A,sentence_B,entailment_label
0,There is no boy playing outdoors and there is ...,A group of kids is playing in a yard and an ol...,NEUTRAL
1,A group of boys in a yard is playing and a man...,The young boys are playing outdoors and the ma...,NEUTRAL
2,A group of children is playing in the house an...,The young boys are playing outdoors and the ma...,NEUTRAL
3,A brown dog is attacking another animal in fro...,A brown dog is attacking another animal in fro...,ENTAILMENT
4,A brown dog is attacking another animal in fro...,A brown dog is helping another animal in front...,NEUTRAL
...,...,...,...
4901,The young girl is blowing a bubble that is huge,There is no girl in pink twirling a ribbon,NEUTRAL
4902,A dog in a colored coat is running across the ...,The flute is being played by one man,NEUTRAL
4903,A boy is happily playing the piano,A white bird is landing swiftly in the water,NEUTRAL
4904,"The girl, who is little, is combing her hair i...",Two people wearing helmets are driving over th...,NEUTRAL
4905,A man is in a parking lot and is playing tenni...,The snowboarder is leaping fearlessly over whi...,NEUTRAL

In [5]:
df["sentence_A"]=original["sentence_A"]
df["sentence_B"]=original["sentence_B"]

In [6]:
df

,relation,no_matcheadas,contradiction,jaccard,simBoW,sumas,mutinf_t,max_info_t,entail,list_comp,list_incomp,Jaro-Winkler_rit,negT,negH,overlap_ent,clases,predictions,sentence_A,sentence_B
0,-1,0.714286,0.142857,0.000000,0.316228,0.101323,4.041253,0.448079,0.500000,2,0,0.491667,0,0,0.142857,NEUTRAL,2,There is no boy playing outdoors and there is ...,A group of kids is playing in a yard and an ol...
1,2,0.750000,0.000000,0.666667,0.428571,0.106182,4.217714,0.578176,0.714286,2,0,0.589286,0,0,0.250000,NEUTRAL,2,A group of boys in a yard is playing and a man...,The young boys are playing outdoors and the ma...
2,-1,0.750000,0.250000,0.333333,0.285714,0.083118,4.088408,0.490766,0.714286,3,0,0.507937,0,0,0.000000,NEUTRAL,2,A group of children is playing in the house an...,The young boys are playing outdoors and the ma...
3,1,0.000000,0.000000,1.000000,0.925820,0.184760,4.683008,1.000000,1.000000,0,0,0.952381,0,0,1.000000,ENTAILMENT,1,A brown dog is attacking another animal in fro...,A brown dog is attacking another animal in fro...
4,2,0.166667,0.000000,0.833333,0.833333,0.151210,4.574526,0.867853,0.857143,0,0,0.822222,0,0,0.833333,NEUTRAL,2,A brown dog is attacking another animal in fro...,A brown dog is helping another animal in front...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4901,-1,0.666667,0.333333,0.250000,0.223607,0.043145,4.076415,0.335569,0.250000,0,0,0.483333,0,0,0.000000,NEUTRAL,2,The young girl is blowing a bubble that is huge,There is no girl in pink twirling a ribbon
4902,2,1.000000,0.000000,0.000000,0.000000,0.051206,3.770053,0.122140,0.500000,2,0,0.344444,0,0,0.000000,NEUTRAL,2,A dog in a colored coat is running across the ...,The flute is being played by one man
4903,2,1.000000,0.000000,0.000000,0.000000,-0.019122,3.697886,0.101417,0.400000,2,0,0.000000,0,0,0.000000,NEUTRAL,2,A boy is happily playing the piano,A white bird is landing swiftly in the water
4904,2,1.000000,0.000000,0.000000,0.000000,-0.017080,3.848196,0.146788,0.250000,2,0,0.420635,0,0,0.000000,NEUTRAL,2,"The girl, who is little, is combing her hair i...",Two people wearing helmets are driving over th...
4905,2,1.000000,0.000000,0.000000,0.000000,0.010754,3.770119,0.156880,0.200000,1,0,0.280952,0,0,0.000000,NEUTRAL,2,A man is in a parking lot and is playing tenni...,The snowboarder is leaping fearlessly over whi...

In [7]:
entailment=df[df["clases"]=="ENTAILMENT"]
neutral=df[df["clases"]=="NEUTRAL"]
contradiction=df[df["clases"]=="CONTRADICTION"]
contradiction

,relation,no_matcheadas,contradiction,jaccard,simBoW,sumas,mutinf_t,max_info_t,entail,list_comp,list_incomp,Jaro-Winkler_rit,negT,negH,overlap_ent,clases,predictions,sentence_A,sentence_B
5,2,0.333333,0.000000,0.333333,0.666667,0.277381,4.410696,0.942602,1.000000,1,0,0.944444,0,0,0.666667,CONTRADICTION,1,Two dogs are wrestling and hugging,There is no dog wrestling and hugging
10,-1,0.000000,0.200000,0.600000,0.800000,0.185405,4.586766,0.919146,1.000000,1,0,0.966667,0,0,0.800000,CONTRADICTION,0,There is no man in a black jacket doing tricks...,A person in a black jacket is doing tricks on ...
13,-1,0.200000,0.200000,0.750000,0.866025,0.386539,4.589580,0.873868,0.800000,0,0,0.916667,0,0,0.800000,CONTRADICTION,0,Nobody is riding the bicycle on one wheel,A person is riding the bicycle on one wheel
16,-1,0.000000,0.200000,0.750000,0.912871,0.361004,4.667369,1.000000,1.000000,0,0,0.944444,0,0,0.800000,CONTRADICTION,0,A man with a jersey is dunking the ball at a b...,There is no man dunking the ball at a basketba...
19,2,0.500000,0.000000,0.500000,0.547723,0.084368,4.238988,0.694347,0.666667,1,0,0.780556,0,0,0.500000,CONTRADICTION,2,The player is missing the basket and a crowd i...,The player is dunking the basketball into the ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4699,-1,0.000000,0.166667,0.750000,1.000000,0.256049,4.761876,1.000000,1.000000,0,0,1.000000,0,0,0.833333,CONTRADICTION,0,The lady is holding the paintbrush next to the...,There is no lady holding the paintbrush next t...
4706,2,0.500000,0.000000,0.666667,0.866025,0.291781,4.588215,0.781620,0.750000,0,0,0.916667,0,1,0.500000,CONTRADICTION,0,A golden retriever is running,A golden retriever is not running
4740,1,0.000000,0.000000,0.800000,0.833333,0.214538,4.544263,0.943765,1.000000,1,0,0.972222,0,0,1.000000,CONTRADICTION,1,A shirtless woman is leading a horse that is p...,A shirtless man is leading a horse that is pul...
4743,2,0.166667,0.000000,1.000000,0.942809,0.185290,4.675417,0.898225,0.888889,0,0,0.962963,0,1,0.833333,CONTRADICTION,0,A young girl is playing on the edge of a fount...,A young girl is playing on the edge of a fount...
4754,-1,0.000000,0.250000,0.750000,1.000000,0.360831,4.813239,1.000000,1.000000,0,0,1.000000,0,0,0.750000,CONTRADICTION,0,There is no cyclist performing a jump on a bic...,A cyclist is performing a jump on a bicycle

In [8]:
df_e=entailment.sample(n=200)
df_n=neutral.sample(n=200)
df_c=contradiction.sample(n=200)
df_t=pd.concat([df_e,df_n,df_c])
df_t

,relation,no_matcheadas,contradiction,jaccard,simBoW,sumas,mutinf_t,max_info_t,entail,list_comp,list_incomp,Jaro-Winkler_rit,negT,negH,overlap_ent,clases,predictions,sentence_A,sentence_B
625,2,0.333333,0.000000,1.000000,0.942809,0.237504,4.520319,0.773784,0.750000,0,0,0.916667,0,0,0.666667,ENTAILMENT,2,Some women are dancing and singing,A woman is dancing and singing with other women
1971,1,0.000000,0.000000,1.000000,0.866025,0.310738,4.640220,1.000000,1.000000,0,0,0.916667,0,0,1.000000,ENTAILMENT,1,A man is recklessly climbing a rope,A man is climbing up a rope
1170,-1,0.500000,0.250000,0.500000,0.377964,0.197095,4.248140,0.648678,0.600000,1,1,0.464286,0,0,0.500000,ENTAILMENT,2,A man is pouring a plate of cheese which is sh...,The lady is adding cheese to the sauce
1279,2,0.333333,0.000000,1.000000,0.707107,0.354545,4.741051,1.000000,1.000000,0,0,0.805556,0,0,0.666667,ENTAILMENT,1,"A girl, who is little, is playing the piano",A little girl is playing the piano
3950,1,0.000000,0.000000,0.666667,1.000000,0.248152,4.786618,1.000000,1.000000,0,0,0.500000,0,0,1.000000,ENTAILMENT,1,Mud is covering a topless woman,A topless woman is being covered in mud
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,2,0.750000,0.000000,0.400000,0.408248,0.138104,4.142034,0.555252,0.666667,2,0,0.805556,0,1,0.250000,CONTRADICTION,2,The woman is cracking eggs into a bowl,The lady isn't breaking raw eggs into a bowl
93,2,0.333333,0.000000,0.666667,0.666667,0.279323,4.489641,0.711084,0.500000,0,1,0.777778,0,0,0.666667,CONTRADICTION,2,A child is hitting a baseball,A child is missing a baseball
3144,2,0.333333,0.000000,0.666667,0.750000,0.287526,4.444299,0.846764,1.000000,1,0,0.833333,0,0,0.666667,CONTRADICTION,1,A man is putting down an electronic device,A man is holding up an electronic device
1128,-1,0.000000,0.333333,0.666667,0.866025,0.304286,4.670316,1.000000,1.000000,0,0,0.916667,1,0,0.666667,CONTRADICTION,0,The man in not playing the flute,The man is playing the flute
798,-1,0.000000,0.333333,0.666667,1.000000,0.280803,4.646705,1.000000,1.000000,0,0,1.000000,0,0,0.666667,CONTRADICTION,0,There is no badger shrewdly digging the earth,A badger is shrewdly digging the earth

In [9]:
df_t=df_t.reset_index(drop=True)
df_t

,relation,no_matcheadas,contradiction,jaccard,simBoW,sumas,mutinf_t,max_info_t,entail,list_comp,list_incomp,Jaro-Winkler_rit,negT,negH,overlap_ent,clases,predictions,sentence_A,sentence_B
0,2,0.333333,0.000000,1.000000,0.942809,0.237504,4.520319,0.773784,0.750000,0,0,0.916667,0,0,0.666667,ENTAILMENT,2,Some women are dancing and singing,A woman is dancing and singing with other women
1,1,0.000000,0.000000,1.000000,0.866025,0.310738,4.640220,1.000000,1.000000,0,0,0.916667,0,0,1.000000,ENTAILMENT,1,A man is recklessly climbing a rope,A man is climbing up a rope
2,-1,0.500000,0.250000,0.500000,0.377964,0.197095,4.248140,0.648678,0.600000,1,1,0.464286,0,0,0.500000,ENTAILMENT,2,A man is pouring a plate of cheese which is sh...,The lady is adding cheese to the sauce
3,2,0.333333,0.000000,1.000000,0.707107,0.354545,4.741051,1.000000,1.000000,0,0,0.805556,0,0,0.666667,ENTAILMENT,1,"A girl, who is little, is playing the piano",A little girl is playing the piano
4,1,0.000000,0.000000,0.666667,1.000000,0.248152,4.786618,1.000000,1.000000,0,0,0.500000,0,0,1.000000,ENTAILMENT,1,Mud is covering a topless woman,A topless woman is being covered in mud
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,2,0.750000,0.000000,0.400000,0.408248,0.138104,4.142034,0.555252,0.666667,2,0,0.805556,0,1,0.250000,CONTRADICTION,2,The woman is cracking eggs into a bowl,The lady isn't breaking raw eggs into a bowl
596,2,0.333333,0.000000,0.666667,0.666667,0.279323,4.489641,0.711084,0.500000,0,1,0.777778,0,0,0.666667,CONTRADICTION,2,A child is hitting a baseball,A child is missing a baseball
597,2,0.333333,0.000000,0.666667,0.750000,0.287526,4.444299,0.846764,1.000000,1,0,0.833333,0,0,0.666667,CONTRADICTION,1,A man is putting down an electronic device,A man is holding up an electronic device
598,-1,0.000000,0.333333,0.666667,0.866025,0.304286,4.670316,1.000000,1.000000,0,0,0.916667,1,0,0.666667,CONTRADICTION,0,The man in not playing the flute,The man is playing the flute
599,-1,0.000000,0.333333,0.666667,1.000000,0.280803,4.646705,1.000000,1.000000,0,0,1.000000,0,0,0.666667,CONTRADICTION,0,There is no badger shrewdly digging the earth,A badger is shrewdly digging the earth

In [13]:
df_t.to_pickle("predictions/RL_SICK_TEST_600.pickle")

In [10]:
lista_respuestasOllama=[]

In [11]:
df.columns

Index(['relation', 'no_matcheadas', 'contradiction', 'jaccard', 'simBoW',
       'sumas', 'mutinf_t', 'max_info_t', 'entail', 'list_comp', 'list_incomp',
       'Jaro-Winkler_rit', 'negT', 'negH', 'overlap_ent', 'clases',
       'predictions', 'sentence_A', 'sentence_B'],
      dtype='object')

In [12]:
faltantes=[]

# RIT base

In [14]:
for i in range(1):
    for index,strings in df_t[i*600:(i+1)*600].iterrows():
        #print(strings["sentence1"],strings["sentence2"],strings['gold_label'])
        prompt = ''''Analyze the following sentences: 
        Text: '''+strings["sentence_A"]+'''
        Hypothesis: '''+ strings["sentence_B"]+'''
        only responds using the template. '''
        #print(prompt)
        data = {
            "prompt": prompt,
            "model": model,
            "format": "json",
            "stream": False,
            #"options": {"temperature": 0.2},
        }
        try:
            response = requests.post("http://localhost:11434/api/generate", json=data, stream=False,timeout=15)        
            json_data = json.loads(response.text)
            lista_respuestasOllama.append(json.dumps(json.loads(json_data["response"]), indent=2))
            print(index)
        except:
            print("SaltÃ³",index)
            faltantes.append(index)
            lista_respuestasOllama.append("NA")
    with open("resultados/rit_base_SICK_TEST_600_"+str(i+1)+".pickle", "wb") as f:
        pickle.dump(lista_respuestasOllama, f)
    print("Primer rango: ",(i)*600,(i+1)*600)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
Primer rango:  0 600

In [17]:
len(lista_respuestasOllama)

600